[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mit-6.006-notes"
authors = [{name = "Jialin Yi", email = "jialin.yi.work@outlook.com"}]
dynamic = ["version", "description"]
